name: 'Asana GitHub Sync'
description: 'Automatically sync GitHub PR states to Asana task custom fields'
author: 'Planning Center'

branding:
  icon: 'check-circle'
  color: 'purple'

inputs:
  asana_token:
    description: 'Asana Personal Access Token'
    required: true
  github_token:
    description: 'GitHub token (use secrets.GITHUB_TOKEN)'
    required: true
  rules:
    description: 'YAML rules configuration for PR event automation'
    required: true

outputs:
  task_ids:
    description: 'Comma-separated list of task IDs found in PR'
  field_updates:
    description: 'Number of field updates applied'

runs:
  using: 'node20'
  main: 'dist/index.js'